CREATE DATABASE TCC;

USE TCC;

CREATE TABLE ESTADO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL UNIQUE,
    SIGLA CHAR(2) NOT NULL UNIQUE,
    ATIVO ENUM('DISPONÍVEL', 'INDISPONÍVEL') NOT NULL DEFAULT 'DISPONÍVEL',
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID)
);

CREATE TABLE CIDADE (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    ATIVO ENUM('DISPONÍVEL', 'INDISPONÍVEL') NOT NULL DEFAULT 'DISPONÍVEL', /* ENUM abreviação de enumeração serve para mostrar as opções disponíveis */
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY (ID),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID),
    CONSTRAINT CIDADE_UNICA UNIQUE(NOME, ESTADO_ID)
);

CREATE TABLE CLIENTE (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    DOCUMENTO VARCHAR(18) NOT NULL UNIQUE,
    ENDERECO VARCHAR(400) NOT NULL,
    ENDERECO_NUMERO INT NOT NULL,
    TELEFONE1 CHAR(14) NOT NULL,
    CONTATO VARCHAR(255),
    CIDADE_ID INT NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_CLI_CID FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID)
);

CREATE TABLE FORNECEDOR (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    DOCUMENTO VARCHAR(18) NOT NULL UNIQUE,
    ENDERECO VARCHAR(255) NOT NULL,
    ENDERECO_NUMERO INT NOT NULL,
    TELEFONE1 VARCHAR(14) NOT NULL,
    CONTATO VARCHAR(255),
    CIDADE_ID INT NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID),
    CONSTRAINT FK_FOR_CID FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE(ID)
);

CREATE TABLE FORNECEDOR_PRODUTO (
    FORNECEDOR_ID INT NOT NULL,
    PRODUTO_ID INT NOT NULL,

    PRIMARY KEY (FORNECEDOR_ID, PRODUTO_ID),

    CONSTRAINT FK_FP_FORNECEDOR
        FOREIGN KEY (FORNECEDOR_ID)
        REFERENCES FORNECEDOR(ID),

    CONSTRAINT FK_FP_PRODUTO
        FOREIGN KEY (PRODUTO_ID)
        REFERENCES PRODUTO(ID)
);

CREATE TABLE PRODUTO_CATEGORIA (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO'
    CONSTRAINT PK_CATEGORIA_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ESTOQUE INT NOT NULL DEFAULT 0,
   STATUS ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO'
    DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CATEGORIA_ID INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORIA_ID) REFERENCES PRODUTO_CATEGORIA (ID)
);

CREATE TABLE Usuarios (
  ID int NOT NULL AUTO_INCREMENT,
  EMAIL varchar(50) NOT NULL UNIQUE,
  SENHA varchar(255) NOT NULL,
  NOME varchar(50) NOT NULL,
  NIVEL ENUM('ADMIN', 'FUNCIONARIO') NOT NULL DEFAULT 'FUNCIONARIO',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; /*Charset é para definir a codificação de caracteres, já que o UTF-8 suporta uma ampla gama de caracteres, e o ENGINE serve para definir o tipo de armazenamento do banco de dados*/

CREATE TABLE MOVIMENTACAO_ESTOQUE (
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    TIPO ENUM('ENTRADA', 'SAIDA') NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_MOVIMENTACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OBSERVACAO VARCHAR(255),

    CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY (ID),

    CONSTRAINT FK_MOV_PRODUTO
        FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID),

    CONSTRAINT FK_MOV_USUARIO
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);








